<Workspace Version="0.6.3.7375" X="-78.7421978461747" Y="136.457232972329" zoom="1.25584483561315" Description="Evaluates if an XYZ is located inside a given room." Category="Clockwork.Revit.Rooms" Name="Is Point In Room" ID="46d97eca-f979-492a-bb58-8545a2425e6f">
  <Elements>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="187de382-0c2f-494a-be7e-1e71e5a7991a" nickname="Input" x="270.918575133166" y="152.020497367308" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Room" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="33aa457e-d78c-447b-a7ef-361bb1d32c07" nickname="Output" x="939.206946234212" y="70.0116033179563" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="bool" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="24a7cafa-e09a-496c-aa0d-76594a1c80df" nickname="Return List Or Single Value" x="714.326346616213" y="71.0385718418202" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="Return List Or Single Value" />
      <Description value="If the list in input #1 has only one item, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="list #1" />
        <Input value="list #2" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="be1ae954-1fb4-45b7-9920-f3375643ec49" nickname="Turn Into List" x="241.481072565006" y="71.5385718418203" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element into a (flat) list" />
      <Inputs>
        <Input value="item" />
      </Inputs>
      <Outputs>
        <Output value="list" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.PythonVarIn type="Dynamo.Nodes.PythonVarIn" guid="4773ee4f-ac24-48a3-8c73-b51c921da7bf" nickname="Python Script With Variable Number of Inputs" x="409.663619281452" y="151.100553267111" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputs="2">
      <Script>import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
import Autodesk

room = IN0
points = IN1
booleans = list()
for point in points:
	try:
		if room.IsPointInRoom(point):
			booleans.append(1)
		else:
			booleans.append(0)
	except:
		booleans.append(list())
OUT = booleans</Script>
    </Dynamo.Nodes.PythonVarIn>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="32029b7a-e637-4eee-8e0b-85d67cfe2f6c" nickname="Input" x="88.5737645110426" y="72.1615192039533" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="XYZ(s)" />
    </Dynamo.Nodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="187de382-0c2f-494a-be7e-1e71e5a7991a" start_index="0" end="4773ee4f-ac24-48a3-8c73-b51c921da7bf" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="24a7cafa-e09a-496c-aa0d-76594a1c80df" start_index="0" end="33aa457e-d78c-447b-a7ef-361bb1d32c07" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="be1ae954-1fb4-45b7-9920-f3375643ec49" start_index="0" end="24a7cafa-e09a-496c-aa0d-76594a1c80df" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="be1ae954-1fb4-45b7-9920-f3375643ec49" start_index="0" end="4773ee4f-ac24-48a3-8c73-b51c921da7bf" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="4773ee4f-ac24-48a3-8c73-b51c921da7bf" start_index="0" end="24a7cafa-e09a-496c-aa0d-76594a1c80df" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="32029b7a-e637-4eee-8e0b-85d67cfe2f6c" start_index="0" end="be1ae954-1fb4-45b7-9920-f3375643ec49" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>