<Workspace Version="0.6.3.7375" X="317.847678221989" Y="248.162650873719" zoom="1.04239626728003" Description="Checks whether a given wall type is a curtain wall" Category="Clockwork.Revit.Wall" Name="Wall Type Is Curtain Wall" ID="3f5cafad-fdbf-4669-82c2-c373652be917">
  <Elements>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="6eaa085b-17a4-441e-964c-b7dd23aa07f0" nickname="Turn Into List" x="-40.0000000000001" y="95.9728260245498" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element into a (flat) list" />
      <Inputs>
        <Input value="item" />
      </Inputs>
      <Outputs>
        <Output value="list" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="7d675e6f-ff05-4b4b-89eb-be20b050e79e" nickname="Input" x="-210" y="95.7142857142857" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Wall Type(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="f6657b38-376f-4e7b-9fb8-9538314be35d" nickname="Output" x="436.595167835944" y="34.2688787742301" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="bool" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.PythonVarIn type="Dynamo.Nodes.PythonVarIn" guid="e8916af6-0865-4083-8b19-a04de06ed944" nickname="Python Script With Variable Number of Inputs" x="130.928333333333" y="35.1252380952386" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputs="2">
      <Script>import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
import Autodesk

doc = IN0
walltypes = IN1
booleans = list()
for item in walltypes:
	try: 
		if str(item.Kind) == 'Curtain':
			booleans.append(1)
		else:
			booleans.append(0)
	except:
		booleans.append(0)
OUT = booleans</Script>
    </Dynamo.Nodes.PythonVarIn>
    <Dynamo.Nodes.RevitDocument type="Dynamo.Nodes.RevitDocument" guid="950dda9a-7f82-441f-97de-59b1a5fc77c7" nickname="Revit Document" x="-31.7502380952386" y="-6.48190476190425" isVisible="true" isUpstreamVisible="true" lacing="Longest" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="6eaa085b-17a4-441e-964c-b7dd23aa07f0" start_index="0" end="e8916af6-0865-4083-8b19-a04de06ed944" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="7d675e6f-ff05-4b4b-89eb-be20b050e79e" start_index="0" end="6eaa085b-17a4-441e-964c-b7dd23aa07f0" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="e8916af6-0865-4083-8b19-a04de06ed944" start_index="0" end="f6657b38-376f-4e7b-9fb8-9538314be35d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="950dda9a-7f82-441f-97de-59b1a5fc77c7" start_index="0" end="e8916af6-0865-4083-8b19-a04de06ed944" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>