<Workspace Version="0.7.5.3566" X="24.9804150173894" Y="289.052599934719" zoom="0.998868722908503" Description="" Category="" Name="Home">
  <Elements>
    <DSRevitNodesUI.Views type="DSRevitNodesUI.Views" guid="14f21254-abe4-47e3-852d-68df333f93e3" nickname="Views" x="538.130135939541" y="107.340862644057" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="1:Level 1" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="fa99068a-67ed-4c9a-95af-441bed6081f2" nickname="Code Block" x="5.02526995538972" y="18.844762332711" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="5;" ShouldFocus="false" />
    <Dynamo.Nodes.Watch type="Dynamo.Nodes.Watch" guid="3f16b264-be62-4962-bcd6-1b2cda19cbef" nickname="Watch" x="1073.4772097329" y="40.6603471187693" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="9a29a1f5-3dc3-4e45-8cdd-b4faab6e3477" nickname="Rectangle.ByWidthHeight" x="219.256582730315" y="2.54235156635829" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Rectangle.ByWidthHeight@double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="303cb93e-8c0a-4e77-9838-10d7328204a2" nickname="Geometry.Explode" x="494.602916583669" y="1.48462925746597" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Explode" />
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="38e573c5-b1c7-4538-abf7-f66097586dd8" nickname="DetailCurve.FromCurve" x="805.771237133477" y="40.3371165726591" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="24214d3e-6159-4b2c-97b4-0a35a13518d9" />
      <Name value="DetailCurve.FromCurve" />
      <Description value="Creates a detail line based on a given curve" />
      <Inputs>
        <Input value="Curve(s)" />
        <Input value="View" />
      </Inputs>
      <Outputs>
        <Output value="DetailCurve(s)" />
      </Outputs>
    </Dynamo.Nodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="14f21254-abe4-47e3-852d-68df333f93e3" start_index="0" end="38e573c5-b1c7-4538-abf7-f66097586dd8" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="fa99068a-67ed-4c9a-95af-441bed6081f2" start_index="0" end="9a29a1f5-3dc3-4e45-8cdd-b4faab6e3477" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fa99068a-67ed-4c9a-95af-441bed6081f2" start_index="0" end="9a29a1f5-3dc3-4e45-8cdd-b4faab6e3477" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="9a29a1f5-3dc3-4e45-8cdd-b4faab6e3477" start_index="0" end="303cb93e-8c0a-4e77-9838-10d7328204a2" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="303cb93e-8c0a-4e77-9838-10d7328204a2" start_index="0" end="38e573c5-b1c7-4538-abf7-f66097586dd8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="38e573c5-b1c7-4538-abf7-f66097586dd8" start_index="0" end="3f16b264-be62-4962-bcd6-1b2cda19cbef" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>