<Workspace Version="0.7.5.3566" X="191.801339068828" Y="313.272890390715" zoom="0.692022144571883" Description="Creates area separation lines from geometry curves. " Category="Clockwork.Revit.Elements.ModelCurve.Create" Name="AreaSeparator.FromCurve" ID="fdc98eeb-e9be-4c20-b9ae-1fa686636067">
  <Elements>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="d233a39a-cfad-4a80-b0e8-859917c5f97f" nickname="Input" x="-2.89008092542656" y="-17.3404855525595" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Curve(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="1cd26b14-cb68-4c9f-b1f2-75c8db318a86" nickname="Output" x="809.079179650833" y="-16.0114639401324" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Area Separator(s)" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="9663d7ec-7e83-43e8-aa70-ba9607d8a183" nickname="Input" x="212.195745705288" y="142.246658971245" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Sketch plane" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="1692d858-5038-4192-880f-5db8e03012db" nickname="Input" x="205.195745705288" y="225.246658971245" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="AreaPlan view" />
    </Dynamo.Nodes.Symbol>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="786d1079-e66a-4b07-a4fd-e72dbefe5739" nickname="Python Script" x="416" y="114.801618508532" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="3">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
curves = UnwrapElement(IN[0])
sketchplane = UnwrapElement(IN[1])
view = UnwrapElement(IN[2])
elementlist = list()

if str(view.ViewType) == "AreaPlan":
	TransactionManager.Instance.EnsureInTransaction(doc)
	doccreation = doc.Create
	for curve in curves:
		separator = doccreation.NewAreaBoundaryLine(sketchplane, curve.ToRevitType(), view)
		elementlist.append(separator)
	TransactionManager.Instance.TransactionTaskDone()
else:
	elementlist = "The active view needs to be an area plan..."
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="aa9e7741-cd0a-4da7-a524-dace66a1ba2d" nickname="Turn Into List" x="218.195745705288" y="57" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="item" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="7557beff-41c3-4f58-815f-c0aa773d115a" nickname="ReturnListOrSingleValue" x="569.116158608817" y="-17.9965016484353" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="item #1 (unknown)" />
        <Input value="item #2 (list)" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="d233a39a-cfad-4a80-b0e8-859917c5f97f" start_index="0" end="aa9e7741-cd0a-4da7-a524-dace66a1ba2d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d233a39a-cfad-4a80-b0e8-859917c5f97f" start_index="0" end="7557beff-41c3-4f58-815f-c0aa773d115a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9663d7ec-7e83-43e8-aa70-ba9607d8a183" start_index="0" end="786d1079-e66a-4b07-a4fd-e72dbefe5739" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="1692d858-5038-4192-880f-5db8e03012db" start_index="0" end="786d1079-e66a-4b07-a4fd-e72dbefe5739" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="786d1079-e66a-4b07-a4fd-e72dbefe5739" start_index="0" end="7557beff-41c3-4f58-815f-c0aa773d115a" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="aa9e7741-cd0a-4da7-a524-dace66a1ba2d" start_index="0" end="786d1079-e66a-4b07-a4fd-e72dbefe5739" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7557beff-41c3-4f58-815f-c0aa773d115a" start_index="0" end="1cd26b14-cb68-4c9f-b1f2-75c8db318a86" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>