<Workspace Version="0.7.5.3566" X="61" Y="309" zoom="1" Description="Retrieves all elements stored in a selection set" Category="Clockwork.Revit.Elements.SelectionSet.Query" Name="SelectionSet.Elements" ID="900424ab-ac1c-4477-8c82-4730ff421744">
  <Elements>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="8ad5e1bc-7c37-4a89-8b4c-ee6e48334442" nickname="Python Script" x="431.5304894143" y="69.7171143365254" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
items = UnwrapElement(IN[0])
elementlist = list()
for item in items:
	selsetmembers = list()
	for member in item.GetElementIds():
		selsetmembers.append(doc.GetElement(member))
	elementlist.append(selsetmembers)
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="0edd4424-f539-4076-889b-4932050edda9" nickname="ReturnListOrSingleValue" x="730.398631791869" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="item #1 (unknown)" />
        <Input value="item #2 (list)" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="5a016026-56ef-4c04-9bc1-24740b6e60c9" nickname="Turn Into List" x="250" y="68.2528438205236" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="item" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="995fec9a-cfbd-4613-abee-07c034ffc048" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="SelectionSet(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="d00741b6-bb69-4450-9e16-9eacca91cdce" nickname="Output" x="997.398631791869" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Elements" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="8ad5e1bc-7c37-4a89-8b4c-ee6e48334442" start_index="0" end="0edd4424-f539-4076-889b-4932050edda9" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="0edd4424-f539-4076-889b-4932050edda9" start_index="0" end="d00741b6-bb69-4450-9e16-9eacca91cdce" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5a016026-56ef-4c04-9bc1-24740b6e60c9" start_index="0" end="8ad5e1bc-7c37-4a89-8b4c-ee6e48334442" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="995fec9a-cfbd-4613-abee-07c034ffc048" start_index="0" end="0edd4424-f539-4076-889b-4932050edda9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="995fec9a-cfbd-4613-abee-07c034ffc048" start_index="0" end="5a016026-56ef-4c04-9bc1-24740b6e60c9" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>