<Workspace Version="0.7.5.3566" X="0" Y="0" zoom="1" Description="Retrieves the corresponding Revit UnitType from a Dynamo UnitType" Category="Clockwork.Revit.Elements.UnitType.Create" Name="UnitType.FromDynamoUnitType" ID="90ad7237-1863-40d0-9a87-05b3be7624b3">
  <Elements>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="978fef7f-2d39-4e4e-bc13-11ba66fbbe4f" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

dynunittype = IN[0]
if str(dynunittype) == 'DynamoUnits.Area':
	ut = UnitType.UT_Area
elif str(dynunittype) == 'DynamoUnits.Length':
	ut = UnitType.UT_Length
elif str(dynunittype) == 'DynamoUnits.Volume':
	ut = UnitType.UT_Volume
else:
	ut = null
OUT = ut</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="1b2d2fac-1cb0-4244-8cc5-d61f77b78658" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Dynamo UnitType" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="1695f946-c505-49f5-9db9-0f7282da27c3" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Revit UnitType" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="978fef7f-2d39-4e4e-bc13-11ba66fbbe4f" start_index="0" end="1695f946-c505-49f5-9db9-0f7282da27c3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1b2d2fac-1cb0-4244-8cc5-d61f77b78658" start_index="0" end="978fef7f-2d39-4e4e-bc13-11ba66fbbe4f" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>