<Workspace Version="0.7.2.2114" X="22.4894192723139" Y="37.6112511539203" zoom="0.768765909448189" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="0d333c3b-9dbc-4e84-a649-4bc76ad76441" nickname="Select Model Element" x="9.76965892397226" y="310.555259242792" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="b808c06a-ff40-4639-b696-b8d3c49a53b0-0010179d" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="ea72e06a-7580-4019-84c0-8a00e9fab388" nickname="Select Model Element" x="9.76965892397226" y="398.299315336861" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="c222719c-4dcb-4e48-98ea-a81db96bf8ce-000f490a" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="daae0de1-9655-4f48-a284-fa12c1e7fcdf" nickname="Select Model Element" x="10.5011244968167" y="486.398402934573" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="b808c06a-ff40-4639-b696-b8d3c49a53b0-00101896" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="c60f135c-5bf7-4723-98e7-88c3eebc343b" nickname="CurveElement.Curve" x="273.939676479554" y="310.555259242792" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.CurveElement.Curve" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="758a2855-b9d2-4b06-9f65-c10e9bfba965" nickname="Code Block" x="287.783131593592" y="653.810385275307" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0..1..#y;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="d4e46709-edda-4f88-bcfc-f8d2865490f9" nickname="Curve.PointAtParameter" x="712.769525789158" y="277.765364932914" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="d1c9c43b-ece3-408b-a191-4167fa75a7dc" nickname="Curve.PointAtParameter" x="712.489412110167" y="512.654673168508" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="0f93a2af-c389-43cd-9b70-887be9ed5967" nickname="CurveElement.Curve" x="274.671142052398" y="486.398402934573" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.CurveElement.Curve" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="835e79c9-0283-4d82-b0cc-766c07242dec" nickname="CurveElement.Curve" x="273.939676479554" y="398.299315336861" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.CurveElement.Curve" />
    <DSCoreNodesUI.CreateList type="DSCoreNodesUI.CreateList" guid="efcea2a6-9361-4eeb-be4e-480cdf23bb83" nickname="List.Create" x="981.606771466725" y="373.163190242595" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="3" />
    <Dynamo.Nodes.IntegerSlider type="Dynamo.Nodes.IntegerSlider" guid="cd3276d4-e1af-4624-9299-ed3c6b9c0809" nickname="Integer Slider" x="10.8318540148371" y="652.761500214821" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Int32>12</System.Int32>
      <Range min="0" max="20" />
    </Dynamo.Nodes.IntegerSlider>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="63caf237-44f3-427a-8d11-ed27a96a56d7" nickname="Curve.PointAtParameter" x="709.465187880232" y="394.128725005095" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.Watch3D type="Dynamo.Nodes.Watch3D" guid="decd73e7-220b-4c44-b969-2be1bb675ec4" nickname="Watch 3D" x="1457.37742384191" y="374.225956269267" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <view width="220" height="326">
        <camera pos_x="20.6975697527232" pos_y="20.6975697527233" pos_z="20.6965697527233" look_x="-20.6975697527232" look_y="-20.6975697527233" look_z="-20.6975697527233" />
      </view>
    </Dynamo.Nodes.Watch3D>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="82c315bb-bbf7-4edc-8610-d3a43d63edd9" nickname="List.Transpose" x="1237.82607181275" y="373.126160291036" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="DSCoreNodes.dll" function="DSCore.List.Transpose@var[]..[]" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="0d333c3b-9dbc-4e84-a649-4bc76ad76441" start_index="0" end="c60f135c-5bf7-4723-98e7-88c3eebc343b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ea72e06a-7580-4019-84c0-8a00e9fab388" start_index="0" end="835e79c9-0283-4d82-b0cc-766c07242dec" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="daae0de1-9655-4f48-a284-fa12c1e7fcdf" start_index="0" end="0f93a2af-c389-43cd-9b70-887be9ed5967" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c60f135c-5bf7-4723-98e7-88c3eebc343b" start_index="0" end="d4e46709-edda-4f88-bcfc-f8d2865490f9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="758a2855-b9d2-4b06-9f65-c10e9bfba965" start_index="0" end="d4e46709-edda-4f88-bcfc-f8d2865490f9" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="758a2855-b9d2-4b06-9f65-c10e9bfba965" start_index="0" end="d1c9c43b-ece3-408b-a191-4167fa75a7dc" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="758a2855-b9d2-4b06-9f65-c10e9bfba965" start_index="0" end="63caf237-44f3-427a-8d11-ed27a96a56d7" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="d4e46709-edda-4f88-bcfc-f8d2865490f9" start_index="0" end="efcea2a6-9361-4eeb-be4e-480cdf23bb83" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d1c9c43b-ece3-408b-a191-4167fa75a7dc" start_index="0" end="efcea2a6-9361-4eeb-be4e-480cdf23bb83" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="0f93a2af-c389-43cd-9b70-887be9ed5967" start_index="0" end="d1c9c43b-ece3-408b-a191-4167fa75a7dc" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="835e79c9-0283-4d82-b0cc-766c07242dec" start_index="0" end="63caf237-44f3-427a-8d11-ed27a96a56d7" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="efcea2a6-9361-4eeb-be4e-480cdf23bb83" start_index="0" end="82c315bb-bbf7-4edc-8610-d3a43d63edd9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="cd3276d4-e1af-4624-9299-ed3c6b9c0809" start_index="0" end="758a2855-b9d2-4b06-9f65-c10e9bfba965" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="63caf237-44f3-427a-8d11-ed27a96a56d7" start_index="0" end="efcea2a6-9361-4eeb-be4e-480cdf23bb83" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="82c315bb-bbf7-4edc-8610-d3a43d63edd9" start_index="0" end="decd73e7-220b-4c44-b969-2be1bb675ec4" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Beispiel-Workflow für das Lab &quot;Einführung in Dynamo - Grafisches Programmieren für Revit&quot; auf der AU Germany 2014. Die Übung basiert in wesentlichen Teilen auf einigen der mit Dynamo ausgelieferten Beispiele.&#xD;&#xA;&#xD;&#xA;- Erstellen einer Reihung von Skelettbauteilen entlang eines durch Modelllinien definierten Dachprofils&#xD;&#xA;- Auslesen der Trägerlängen&#xD;&#xA;- Filtern der Träger nach Trägerlänge&#xD;&#xA;- Elementweises Überschreiben der gefilterten Träger im Modell&#xD;&#xA;&#xD;&#xA;Fragen können Sie gerne an dieckmann@caad.arch.rwth-aachen.de richten." x="9.11144020784047" y="9.20090830839416" />
    <Dynamo.Models.NoteModel text="Auswahl der Modellinien für das Dachprofil" x="8.42562380276343" y="269.616364620888" />
    <Dynamo.Models.NoteModel text="Anzahl Träger" x="12.8944446832712" y="612.32606284605" />
    <Dynamo.Models.NoteModel text="Dynamo Linien aus Revit Linien" x="274.78615637939" y="270.814159264427" />
    <Dynamo.Models.NoteModel text="Erstellen einer Liste von normalisierten Kurvenparametern zum Aufteilen der Linien" x="285.166040327834" y="600.653108580889" />
    <Dynamo.Models.NoteModel text="Erstellen einer Reihe von Punkten auf allen Linien" x="663.971647921195" y="221.448620553249" />
    <Dynamo.Models.NoteModel text="Punktliste für alle drei Linien bilden - und dann Spalten und Reihen vertauschen" x="1033.48050565746" y="315.251564283817" />
  </Notes>
</Workspace>